version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
  rails:
    build:
      context: .
    command: bash --login -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
  webpack:
    build:
      context: .
    command: bash --login -c "bin/webpack-dev-server"
    volumes:
      - .:/app
    ports:
    - "3035:3035"
    environment:
      WEBPACKER_DEV_SERVER_HOST: "0.0.0.0"
