name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    env:
      RAILS_ENV: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Ruby version
        run: ruby -v
      - name: Setup app
        run: ./bin/setup
      - name: Compile webpack for Capybara tests
        run: bundle exec rake webpacker:compile
      - name: ImageMagick version
        run: convert --version
      - name: Ghostscript version
        run: gs --version
      - name: Change ImageMagick policy to allow pdf->png conversion.
        run: |
          sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
      - name: Run tests
        run: bundle exec rake
